---
- name: Random failure
  connection: local
  gather_facts: False
  hosts: all
  tasks:
  - set_fact:
      random_number_1: "{{ 100 | random }}"
      random_number_2: "{{ 100 | random }}"
      random_number_3: "{{ 100 | random }}"
      random_number_4: "{{ 100 | random }}"
      random_number_5: "{{ 100 | random }}"
  - debug: 
      msg: "var 1 {{ random_number_1 }}"
  - debug: 
      msg: "var 2 {{ random_number_2 }}"
  - debug: 
      msg: "var 3 {{ random_number_3 }}"
  - debug: 
      msg: "var 4 {{ random_number_4 }}"
  - debug: 
      msg: "var 5 {{ random_number_5 }}"
  - name: "test fail task 1"
    fail:
      msg: "Failed task 1"
    when: random_number_1|int > 50
  - name: "test fail task 2"
    fail:
      msg: "Failed task 2"
    when: random_number_2|int > 50
  - name: "test fail task 3"
    fail:
      msg: "Failed task 3"
    when: random_number_3|int > 50
  - name: "test fail task 4"
    fail:
      msg: "Failed task 4"
    when: random_number_4|int > 50
  - name: "test fail task 5"
    fail:
      msg: "Failed task 5"
    when: random_number_5|int > 50

  